[build]
  command = ""
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
[build.environment]
  PHP_VERSION = "8.2"
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[dev]
  command = "php -S 0.0.0.0:8888"
  targetPort = 8888
  publish = "."
  framework = "#custom"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "@netlify/plugin-sitemap"
  
[context.production.environment]
  NODE_ENV = "production"
